apiVersion: v1
kind: Pod
metadata:
  name: podman-micro-svc
spec:
  containers:
  - name: awx-mock-server
    image: awx-mock-server:latest
    ports:
    - containerPort: 80
      hostPort: 40001
      hostIp: 0.0.0.0
    volumeMounts:
    - mountPath: /app:z
      name: current-directory
    command: ["uvicorn"]
    args: ["main:app", "--reload", "--port", "80", "--host", "0.0.0.0"]
    tty: true
  volumes:
  - name: current-directory
    hostPath:
      path: ./
      type: Directory